module.exports = {
  prefix: '_tn-',
  important: false,
  separator: ':',
  theme: {
    screens: {
      sm: '800px',
      lg: '1024px',
      xl: '1190px'
    },
    spacing: {
      px: '1px',
      xs: 'var(--size-xs)',
      sm: 'var(--size-sm)',
      md: 'var(--size-md)',
      lg: 'var(--size-lg)',
      xl: 'var(--size-xl)',
      xxl: 'var(--size-xxl)',
      big: 'var(--size-big)',
      max: 'var(--size-max)'
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      lighter: 'var(--cl-lighter)',
      bg: 'var(--cl-bg)',
      featured: 'var(--cl-featured)',
      tune: {
        300: 'var(--cl-tune-300)',
        DEFAULT: 'var(--cl-tune-500)',
        600: 'var(--cl-tune-600)',
        900: 'var(--cl-tune-900)',
      },

      primary: {
        300: 'var(--cl-primary-300)',
        DEFAULT: 'var(--cl-primary-500)',
        600: 'var(--cl-primary-600)',
        800: 'var(--cl-primary-800)',
        900: 'var(--cl-primary-900)',
      },
      secondary: {
        300: 'var(--cl-secondary-300)',
        DEFAULT: 'var(--cl-secondary-500)',
        600: 'var(--cl-secondary-600)',
        900: 'var(--cl-secondary-900)',
      },
      gray: {
        100: 'var(--cl-gray-100)',
        DEFAULT: 'var(--cl-gray-500)'
      }
    },
    backgroundColor: (theme) => theme('colors'),
    backgroundImage: {},
    backgroundOpacity: (theme) => theme('opacity'),
    borderColor: (theme) => ({
      ...theme('colors'),
      default: theme('colors.gray.300', 'currentColor')
    }),
    borderOpacity: (theme) => theme('opacity'),
    borderRadius: {
      none: '0',
      sm: '0.125rem',
      default: 'var(--box-radius)',
      md: '0.375rem',
      lg: '0.5rem',
      full: '9999px'
    },
    borderWidth: {
      default: '1px',
      0: '0',
      2: '2px',
      4: '4px',
      8: '8px'
    },
    boxShadow: {},
    container: {},
    flex: {
      1: '1 1 0%',
      auto: '1 1 auto',
      initial: '0 1 auto',
      none: 'none'
    },
    flexShrink: {
      0: '0',
      default: '1'
    },
    fontFamily: {
      base: ['var(--font-base)']
    },
    fontSize: {
      xs: '13px',
      sm: '15px',
      base: '16px',
      lg: '18px',
      xl: '20px',
      '2xl': '42px',
      '3xl': '55px'
    },
    fontWeight: {
      hairline: '100',
      thin: '200',
      light: '300',
      normal: '400',
      medium: '500',
      semibold: '600',
      bold: '700',
      extrabold: '800',
      black: '900'
    },
    height: (theme) => ({
      auto: 'auto',
      ...theme('spacing'),
      full: '100%',
      screen: '100vh'
    }),
    letterSpacing: {
      tine: '0.6px',
      normal: '0'
    },
    margin: (theme, { negative }) => ({
      auto: 'auto',
      ...theme('spacing'),
      ...negative(theme('spacing'))
    }),
    maxHeight: {
      full: '100%',
      screen: '100vh'
    },
    maxWidth: (theme, { breakpoints }) => ({
      none: 'none',
      xs: '20rem',
      sm: '24rem',
      md: '28rem',
      lg: '32rem',
      xl: '36rem',
      '2xl': '42rem',
      '3xl': '48rem',
      '4xl': '56rem',
      '5xl': '64rem',
      '6xl': '72rem',
      full: '100%',
      ...breakpoints(theme('screens'))
    }),
    minHeight: {
      0: '0',
      full: '100%',
      120: '120px',
      screen: '100vh'
    },
    minWidth: {
      0: '0',
      full: '100%'
    },
    opacity: {
      0: '0',
      25: '0.25',
      50: '0.5',
      75: '0.75',
      100: '1'
    },
    order: {
      first: '-9999',
      last: '9999',
      none: '0',
      1: '1',
      2: '2',
      3: '3',
      4: '4',
      5: '5',
      6: '6',
      7: '7',
      8: '8',
      9: '9',
      10: '10',
      11: '11',
      12: '12'
    },
    padding: (theme) => theme('spacing'),
    space: (theme, { negative }) => ({
      ...theme('spacing'),
      ...negative(theme('spacing'))
    }),
    stroke: {
      current: 'currentColor'
    },
    textColor: (theme) => theme('colors'),
    textOpacity: (theme) => theme('opacity'),
    width: (theme) => ({
      auto: 'auto',
      ...theme('spacing'),
      '1/2': '50%',
      '1/3': '33.333333%',
      '2/3': '66.666667%',
      '1/4': '25%',
      '2/4': '50%',
      '3/4': '75%',
      '1/5': '20%',
      '2/5': '40%',
      '3/5': '60%',
      '4/5': '80%',
      '1/6': '16.666667%',
      '2/6': '33.333333%',
      '3/6': '50%',
      '4/6': '66.666667%',
      '5/6': '83.333333%',
      '1/12': '8.333333%',
      '2/12': '16.666667%',
      '3/12': '25%',
      '4/12': '33.333333%',
      '5/12': '41.666667%',
      '6/12': '50%',
      '7/12': '58.333333%',
      '8/12': '66.666667%',
      '9/12': '75%',
      '10/12': '83.333333%',
      '11/12': '91.666667%',
      full: '100%',
      screen: '100vw'
    }),
    transitionDuration: {
      75: '75ms',
      100: '100ms',
      150: '150ms',
      200: '200ms',
      300: '300ms',
      500: '500ms',
      700: '700ms',
      1000: '1000ms'
    },
    transitionDelay: {
      75: '75ms',
      1: '150ms',
      2: '300ms',
      3: '450ms',
      4: '600ms',
      5: '740ms',
      6: '900ms',
      8: '1000ms',
      9: '1150ms',
      10: '1300ms'
    }
  },
  variants: {
    alignContent: ['responsive'],
    alignItems: ['responsive'],
    alignSelf: ['responsive'],
    backgroundColor: ['responsive', 'hover', 'focus'],
    backgroundOpacity: ['responsive', 'hover', 'focus'],
    backgroundSize: ['responsive'],
    boxShadow: ['responsive', 'hover', 'focus'],
    display: ['responsive'],
    flex: ['responsive'],
    flexDirection: ['responsive'],
    flexGrow: ['responsive'],
    flexShrink: ['responsive'],
    flexWrap: ['responsive'],
    fontFamily: ['responsive'],
    fontSize: ['responsive'],
    fontVariantNumeric: ['responsive'],
    fontStyle: ['responsive'],
    fontWeight: ['responsive', 'hover', 'focus'],
    height: ['responsive'],
    justifyContent: ['responsive'],
    justifyItems: ['responsive'],
    justifySelf: ['responsive'],
    letterSpacing: ['responsive'],
    lineHeight: ['responsive'],
    listStylePosition: ['responsive'],
    listStyleType: ['responsive'],
    margin: ['responsive'],
    maxHeight: ['responsive'],
    maxWidth: ['responsive'],
    minHeight: ['responsive'],
    minWidth: ['responsive'],
    opacity: ['responsive', 'hover', 'focus'],
    order: ['responsive'],
    padding: ['responsive'],
    space: ['responsive'],
    textAlign: ['responsive'],
    textColor: ['responsive', 'hover', 'focus'],
    textOpacity: ['responsive', 'hover', 'focus'],
    verticalAlign: ['responsive'],
    width: ['responsive'],
    transitionDuration: ['responsive'],
    transitionDelay: ['responsive'],
    accessibility: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundClip: [],
    backgroundImage: [],
    gradientColorStops: [],
    backgroundPosition: [],
    backgroundRepeat: [],
    borderCollapse: [],
    borderColor: [],
    borderOpacity: [],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxSizing: [],
    container: [],
    cursor: [],
    divideColor: [],
    divideOpacity: [],
    divideStyle: [],
    divideWidth: [],
    fill: [],
    float: [],
    clear: [],
    fontSmoothing: [],
    inset: [],
    objectFit: [],
    objectPosition: [],
    overflow: [],
    overscrollBehavior: [],
    placeContent: [],
    placeItems: [],
    placeSelf: [],
    placeholderColor: [],
    placeholderOpacity: [],
    pointerEvents: [],
    position: [],
    resize: [],
    stroke: [],
    strokeWidth: [],
    tableLayout: [],
    textDecoration: [],
    textTransform: [],
    userSelect: [],
    visibility: [],
    whitespace: [],
    wordBreak: [],
    zIndex: [],
    gap: [],
    gridAutoFlow: [],
    gridTemplateColumns: ['responsive'],
    gridColumn: [],
    gridColumnStart: [],
    gridColumnEnd: [],
    gridTemplateRows: [],
    gridRow: [],
    gridRowStart: [],
    gridRowEnd: [],
    transform: [],
    transformOrigin: [],
    scale: [],
    rotate: [],
    translate: [],
    transitionProperty: [],
    transitionTimingFunction: [],
    animation: []
  },
  plugins: []
};
